name: CI

on:
  push:
    branches:
      - main

jobs:
  build_and_publish:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge data into main
        run: |
          git fetch origin
          git merge origin/data --no-ff

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

