name: Merge main into data

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  merge-main-into-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Merge main into data
        run: |
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git checkout data
          git merge main
          git push origin data
