name: Fetch new workshop items daily

on:
  workflow_dispatch:
  schedule:
    - cron: "06 22 * * *"

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: "data"

      - uses: denoland/setup-deno@v2
        with:
          working-directory: ./scripts

      - name: Run script
        run: deno run --allow-net --allow-read=../public/ --allow-write=../public/ crawlNew.ts "stages"
        working-directory: ./scripts

      - name: Run script
        run: deno run --allow-net --allow-read=../public/ --allow-write=../public/ crawlNew.ts "characters"
        working-directory: ./scripts

      - name: Commit and push if it changed
        id: commit_and_push
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -f public/wsdata
          timestamp=$(date -u)
          git commit -m "Add new WS items (${timestamp})" || exit 0
          git push
          echo "changed=true" >> "$GITHUB_OUTPUT"
    outputs:
      changed: ${{ steps.commit_and_push.outputs.changed }}

  build:
    needs: fetch
    if: needs.fetch.outputs.changed == 'true'
    permissions:
      pages: write
      id-token: write
      contents: write
    uses: ./.github/workflows/build.yaml
